apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-v1
  labels:
    app: guestbook
    version: "1.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
        version: "1.0"
    spec:
      containers:
      - name: guestbook
        resources:
          limits:
            cpu: 1
            memory: 512M
        image: rojanjose/guestbook-nodejs:mongo
        imagePullPolicy: Always
        ports:
        - name: http-server
          containerPort: 3000
        env:
          - name: MONGO_HOST
            valueFrom: 
              configMapKeyRef:
                name: mongo-config
                key: mongo_host
          - name: MONGO_PORT
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo_port
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: username
          - name: MONGO_PASS
            valueFrom:
              secretKeyRef:
                name: mongodb
                key: password
          - name: MONGO_DB
            valueFrom:
              configMapKeyRef:
                name: mongo-config
                key: mongo_db_name

